{{- if .Values.volume.enabled }}
{{- if .Values.volume.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: ingress-{{ template "seaweedfs.name" . }}-volume
  namespace: {{ .Release.Namespace }}
  {{- with .Values.volume.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: volume
spec:
  ingressClassName: {{ .Values.volume.ingress.className | quote }}
  tls:
    {{ .Values.volume.ingress.tls | default list | toYaml | nindent 6 }}
  rules:
    - http:
        paths:
          - path: {{ .Values.volume.ingress.path | quote }}
            pathType: {{ .Values.volume.ingress.pathType | quote }}
            backend:
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ template "seaweedfs.name" . }}-volume
                port:
                  number: {{ .Values.volume.port }}
                  #name:
{{- else }}
              serviceName: {{ template "seaweedfs.name" . }}-volume
              servicePort: {{ .Values.volume.port }}
{{- end }}
{{- end }}
{{- end }}
