sudo: false
language: go
go:
  - 1.16.x

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - export CGO_ENABLED="0"
  - go env

script:
  - env GO111MODULE=on go test ./weed/...

before_deploy:
  - make release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ERL986+ncQ8lwAJUYDrQ8s2/FxF/cyNIwJIFCqspnWxQgGNNyokET9HapmlPSxjpFRF0q6L2WCg9OY3mSVRq4oI6hg1igOQ12KlLyN71XSJ3c8w0Ay5ho48TQ9l3f3Iu97mntBCe9l0R9pnT8wj1VI8YJxloXwUMG2yeTjA9aBI=
  file:
    - build/linux_arm.tar.gz
    - build/linux_arm64.tar.gz
    - build/linux_386.tar.gz
    - build/linux_amd64.tar.gz
    - build/linux_amd64_large_disk.tar.gz
    - build/darwin_amd64.tar.gz
    - build/darwin_amd64_large_disk.tar.gz
    - build/windows_386.zip
    - build/windows_amd64.zip
    - build/windows_amd64_large_disk.zip
    - build/freebsd_arm.tar.gz
    - build/freebsd_amd64.tar.gz
    - build/freebsd_386.tar.gz
    - build/netbsd_arm.tar.gz
    - build/netbsd_amd64.tar.gz
    - build/netbsd_386.tar.gz
    - build/openbsd_arm.tar.gz
    - build/openbsd_amd64.tar.gz
    - build/openbsd_386.tar.gz
  on:
    tags: true
    repo: chrislusf/seaweedfs
    go: 1.16.x
