version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 9333:9333
      - 19333:19333
    command: 'master -ip=master -ip.bind=0.0.0.0'
  volume:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -ip=volume -master="master:9333" -ip.bind=0.0.0.0 -port=8080'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -ip=filer -master="master:9333" -ip.bind=0.0.0.0'
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0'
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
