apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" . }}-volume
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: volume
spec:
  clusterIP: None
  ports:
  - name: "swfs-volume"
    port: {{ .Values.volume.port }}
    targetPort: {{ .Values.volume.port }}
    protocol: TCP
  - name: "swfs-volume-18080"
    port: {{ .Values.volume.grpcPort }}
    targetPort: {{ .Values.volume.grpcPort }}
    protocol: TCP
{{- if .Values.volume.metricsPort }}
  - name: "swfs-volume-metrics"
    port: {{ .Values.volume.metricsPort }}
    targetPort: {{ .Values.volume.metricsPort }}
    protocol: TCP
{{- end }}
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: volume