# This is a basic workflow to help you get started with Actions

name: Build Versioned Releases

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd, netbsd, openbsd]
        goarch: [amd64, arm, arm64, 386, ppc64le, s390x]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: 386
            goos: darwin
          - goarch: ppc64le
            goos: darwin
          - goarch: s390x
            goos: darwin
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
          - goarch: ppc64le
            goos: windows
          - goarch: s390x
            goos: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.19
        with:
          goversion: 1.17
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          pre_command: export CGO_ENABLED=0
          # build_flags: -tags 5BytesOffset # optional, default is
          ldflags: -extldflags -static -X github.com/chrislusf/seaweedfs/weed/util.COMMIT=${{github.sha}}
          # Where to run `go build .`
          project_path: weed
          binary_name: weed
          asset_name: "${{ matrix.goos }}_${{ matrix.goarch }}"
      - name: Go Release Large Disk Binaries
        uses: wangyoucao577/go-release-action@v1.19
        with:
          goversion: 1.17
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          pre_command: export CGO_ENABLED=0
          build_flags: -tags 5BytesOffset # optional, default is
          ldflags: -extldflags -static -X github.com/chrislusf/seaweedfs/weed/util.COMMIT=${{github.sha}}
          # Where to run `go build .`
          project_path: weed
          binary_name: weed
          asset_name: "${{ matrix.goos }}_${{ matrix.goarch }}_large_disk"
